name: Demo Data
language: csharp
variables:
  - name: Topic
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: f1-data
    required: true
dockerfile: build/dockerfile
runEntryPoint: Bridge.Console.csproj
defaultFile: Bridge.Console/Program.cs
